//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiChartManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaiChartManager.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到配对的 ACB 文件: {0}.
        /// </summary>
        internal static string AcbNotFound {
            get {
                return ResourceManager.GetString("AcbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 激活码无效.
        /// </summary>
        internal static string ActivationCodeInvalid {
            get {
                return ResourceManager.GetString("ActivationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赞助版功能已激活，谢谢你.
        /// </summary>
        internal static string ActivationSuccess {
            get {
                return ResourceManager.GetString("ActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到配对的 AWB 文件: {0}.
        /// </summary>
        internal static string AwbNotFound {
            get {
                return ResourceManager.GetString("AwbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览器窗口未初始化.
        /// </summary>
        internal static string BrowserNotInitialized {
            get {
                return ResourceManager.GetString("BrowserNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看起来配置文件损坏了…已经重置配置文件.
        /// </summary>
        internal static string ConfigCorrupted {
            get {
                return ResourceManager.GetString("ConfigCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不太对劲.
        /// </summary>
        internal static string ConfigCorruptedTitle {
            get {
                return ResourceManager.GetString("ConfigCorruptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换失败: {0}.
        /// </summary>
        internal static string ConvertFailed {
            get {
                return ResourceManager.GetString("ConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换完成！.
        /// </summary>
        internal static string ConvertSuccess {
            get {
                return ResourceManager.GetString("ConvertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未选择文件.
        /// </summary>
        internal static string FileNotSelected {
            get {
                return ResourceManager.GetString("FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未指定游戏目录.
        /// </summary>
        internal static string GameDirNotSpecified {
            get {
                return ResourceManager.GetString("GameDirNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取游戏版本号，可能是因为 A000\DataConfig.xml 找不到或者有错误.
        /// </summary>
        internal static string GameVersionError {
            get {
                return ResourceManager.GetString("GameVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取游戏版本号，解析数据失败.
        /// </summary>
        internal static string GameVersionNotFound {
            get {
                return ResourceManager.GetString("GameVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string GameVersionNotFoundTitle {
            get {
                return ResourceManager.GetString("GameVersionNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相同的资源目录里已经存在一个 ID 相同的流派了.
        /// </summary>
        internal static string GenreIdExists {
            get {
                return ResourceManager.GetString("GenreIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一个优先级更高的资源目录里已经存在一个 ID 相同的流派了，这样的话，新创建的流派不会被识别
        ///如果你确实想新建的话，请先删除以下目录中已存在的流派.
        /// </summary>
        internal static string GenreIdExistsHigherPriority {
            get {
                return ResourceManager.GetString("GenreIdExistsHigherPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化数据目录时出错.
        /// </summary>
        internal static string InitDataDirError {
            get {
                return ResourceManager.GetString("InitDataDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string LauncherExit {
            get {
                return ResourceManager.GetString("LauncherExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏目录.
        /// </summary>
        internal static string LauncherGameDir {
            get {
                return ResourceManager.GetString("LauncherGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要登录.
        /// </summary>
        internal static string LauncherNeedLogin {
            get {
                return ResourceManager.GetString("LauncherNeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开放到局域网.
        /// </summary>
        internal static string LauncherOpenToLan {
            get {
                return ResourceManager.GetString("LauncherOpenToLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择游戏目录.
        /// </summary>
        internal static string LauncherSelectGameDir {
            get {
                return ResourceManager.GetString("LauncherSelectGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        internal static string LauncherStart {
            get {
                return ResourceManager.GetString("LauncherStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开机自动运行.
        /// </summary>
        internal static string LauncherStartup {
            get {
                return ResourceManager.GetString("LauncherStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string LauncherStop {
            get {
                return ResourceManager.GetString("LauncherStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载分类数据 {0} 失败: {1}.
        /// </summary>
        internal static string LoadGenreDataFailed {
            get {
                return ResourceManager.GetString("LoadGenreDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载乐曲数据 {0} 失败: {1}.
        /// </summary>
        internal static string LoadMusicDataFailed {
            get {
                return ResourceManager.GetString("LoadMusicDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载版本数据 {0} 失败: {1}.
        /// </summary>
        internal static string LoadVersionDataFailed {
            get {
                return ResourceManager.GetString("LoadVersionDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前资源目录里已经存在这个 ID 了.
        /// </summary>
        internal static string MusicIdExists {
            get {
                return ResourceManager.GetString("MusicIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入激活码.
        /// </summary>
        internal static string OfflineActivationPrompt {
            get {
                return ResourceManager.GetString("OfflineActivationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线激活.
        /// </summary>
        internal static string OfflineActivationTitle {
            get {
                return ResourceManager.GetString("OfflineActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告：路径中包含特殊字符或中文，可能会导致 MelonLoader 之类的工具出现兼容性问题，请将目录移动至英文路径！.
        /// </summary>
        internal static string PathContainsSpecialChars {
            get {
                return ResourceManager.GetString("PathContainsSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string PathContainsSpecialCharsTitle {
            get {
                return ResourceManager.GetString("PathContainsSpecialCharsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的路径不存在！.
        /// </summary>
        internal static string PathNotExist {
            get {
                return ResourceManager.GetString("PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的路径中看起来不包含游戏文件，请选择 Sinmai.exe 所在的文件夹.
        /// </summary>
        internal static string PathNotGameDir {
            get {
                return ResourceManager.GetString("PathNotGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择资源目录（OPT）的文件夹.
        /// </summary>
        internal static string SelectAssetDirectory {
            get {
                return ResourceManager.GetString("SelectAssetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的图片格式.
        /// </summary>
        internal static string UnsupportedImageFormat {
            get {
                return ResourceManager.GetString("UnsupportedImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相同的资源目录里已经存在一个 ID 相同的版本了.
        /// </summary>
        internal static string VersionIdExists {
            get {
                return ResourceManager.GetString("VersionIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一个优先级更高的资源目录里已经存在一个 ID 相同的版本了，这样的话，新创建的版本不会被识别
        ///如果你确实想新建的话，请先删除以下目录中已存在的版本.
        /// </summary>
        internal static string VersionIdExistsHigherPriority {
            get {
                return ResourceManager.GetString("VersionIdExistsHigherPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 运行时未安装，在启动之后可能会白屏…
        ///
        ///如果你觉得你已经安装了 WebView2 运行时，请尝试重启电脑。
        ///
        ///要尝试安装一下 WebView2 吗？.
        /// </summary>
        internal static string WebView2NotInstalled {
            get {
                return ResourceManager.GetString("WebView2NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 未安装.
        /// </summary>
        internal static string WebView2NotInstalledTitle {
            get {
                return ResourceManager.GetString("WebView2NotInstalledTitle", resourceCulture);
            }
        }
    }
}
