name: Build Canary

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install and Build
      working-directory: MaiChartManager/Front
      run: |
        pnpm install
        pnpm build

    - name: Upload wwwroot
      uses: actions/upload-artifact@v4
      with:
        name: wwwroot
        path: MaiChartManager/wwwroot

  build:
    name: Build
    runs-on: windows-latest
    needs: build-frontend
    
    steps:
    - run: git config --global core.longPaths true
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Download wwwroot
      uses: actions/download-artifact@v4
      with:
        name: wwwroot
        path: MaiChartManager/wwwroot

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build and Publish
      shell: powershell
      run: |
        dotnet build AquaMai/AquaMai.Config.HeadlessLoader/AquaMai.Config.HeadlessLoader.csproj -c Release
        dotnet build MaiLib/MaiLib.csproj -c Release
        dotnet build SimaiSharp/SimaiSharp/SimaiSharp.csproj -c Release
        dotnet build MuConvert/MuConvert.csproj -c Release
        dotnet build SonicAudioTools/Source/SonicAudioLib/SonicAudioLib.csproj -c Release
        dotnet build XV2-Tools/LB_Common/LB_Common.csproj -c Release
        dotnet build XV2-Tools/Xv2CoreLib/Xv2CoreLib.csproj -c Release

        New-Item -ItemType Directory -Force -Path "XV2-Tools/LB_Common/bin/Crack/"
        Copy-Item "XV2-Tools/LB_Common/bin/Release/netstandard2.1/LB_Common.dll" -Destination "XV2-Tools/LB_Common/bin/Crack/LB_Common.dll" -Force
        
        New-Item -ItemType Directory -Force -Path "MaiLib/obj/Crack/net9.0/ref/"
        Copy-Item "MaiLib/bin/Release/net9.0/ref/MaiLib.dll" -Destination "MaiLib/obj/Crack/net9.0/ref/MaiLib.dll" -Force
        
        New-Item -ItemType Directory -Force -Path "MuConvert/obj/Crack/net10.0/win-x64/ref/"
        Copy-Item "MuConvert/bin/Release/net10.0/win-x64/ref/MuConvert.dll" -Destination "MuConvert/obj/Crack/net10.0/win-x64/ref/MuConvert.dll" -Force
        
        New-Item -ItemType Directory -Force -Path "SimaiSharp/SimaiSharp/bin/Crack/netstandard2.1/"
        Copy-Item "SimaiSharp/SimaiSharp/bin/Release/netstandard2.1/SimaiSharp.dll" -Destination "SimaiSharp/SimaiSharp/bin/Crack/netstandard2.1/SimaiSharp.dll" -Force
        
        New-Item -ItemType Directory -Force -Path "SonicAudioTools/Source/SonicAudioLib/bin/Crack/"
        Copy-Item "SonicAudioTools/Source/SonicAudioLib/bin/Release/SonicAudioLib.dll" -Destination "SonicAudioTools/Source/SonicAudioLib/bin/Crack/SonicAudioLib.dll" -Force
        
        New-Item -ItemType Directory -Force -Path "XV2-Tools/Xv2CoreLib/bin/Crack/"
        Copy-Item "XV2-Tools/Xv2CoreLib/bin/Release/Xv2CoreLib.dll" -Destination "XV2-Tools/Xv2CoreLib/bin/Crack/Xv2CoreLib.dll" -Force
        
        dotnet publish MaiChartManager/MaiChartManager.csproj -c Crack -o ./publish /p:BuildProjectReferences=false
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MaiChartManager-Crack
        path: ./publish
